# Generated by Django 5.2.4 on 2025-08-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bid_price_cents', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(max_length=63)),
            ],
        ),
    ]
