# Generated by Django 5.2.4 on 2025-08-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid_price_cents',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
