# Generated by Django 5.2.4 on 2025-08-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_bid_price_cents_listing_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='users_watching', to='auctions.listing'),
        ),
    ]
